{"pageProps":{"content":"[[\"$r\",\"MaxWidth\",\"last\",{\"children\":[[\"$r\",\"Intro\",null,{\"children\":[\"$r\",\"p\",null,{\"children\":\"In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.\"}]}],\"\\n\",[\"$r\",\"p\",null,{\"children\":\"We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original error message.\"}],\"\\n\",[\"$r\",\"p\",null,{\"children\":\"The full text of the error you just encountered is:\"}],\"\\n\",[\"$r\",\"ErrorDecoder\",null,{}]]}]]","toc":"[]","meta":{},"errorCode":"460","errorMessage":"Suspense Exception: This is not a real error! It's an implementation detail of `use` to interrupt the current render. You must either rethrow it immediately, or move the `use` call outside of the `try/catch` block. Capturing without rethrowing will lead to unexpected behavior.\n\nTo handle async errors, wrap your component in an error boundary, or call the promise's `.catch` method and pass the result to `use`"},"__N_SSG":true}